// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/mail/mail.proto

package mail

import (
	reflect "reflect"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_proto_mail_mail_proto protoreflect.FileDescriptor

const file_proto_mail_mail_proto_rawDesc = "" +
	"\n" +
	"\x15proto/mail/mail.proto\x12\x04mail\x1a\x1fproto/mail/type/send_mail.proto2}\n" +
	"\vMailService\x123\n" +
	"\bSendMail\x12\x11.mail.MailRequest\x1a\x12.mail.MailResponse\"\x00\x129\n" +
	"\vNewSendMail\x12\x14.mail.NewMailRequest\x1a\x12.mail.MailResponse\"\x00B\x0fZ\rgenproto/mailb\x06proto3"

var file_proto_mail_mail_proto_goTypes = []any{
	(*MailRequest)(nil),    // 0: mail.MailRequest
	(*NewMailRequest)(nil), // 1: mail.NewMailRequest
	(*MailResponse)(nil),   // 2: mail.MailResponse
}
var file_proto_mail_mail_proto_depIdxs = []int32{
	0, // 0: mail.MailService.SendMail:input_type -> mail.MailRequest
	1, // 1: mail.MailService.NewSendMail:input_type -> mail.NewMailRequest
	2, // 2: mail.MailService.SendMail:output_type -> mail.MailResponse
	2, // 3: mail.MailService.NewSendMail:output_type -> mail.MailResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_mail_mail_proto_init() }
func file_proto_mail_mail_proto_init() {
	if File_proto_mail_mail_proto != nil {
		return
	}
	file_proto_mail_type_send_mail_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_mail_mail_proto_rawDesc), len(file_proto_mail_mail_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_mail_mail_proto_goTypes,
		DependencyIndexes: file_proto_mail_mail_proto_depIdxs,
	}.Build()
	File_proto_mail_mail_proto = out.File
	file_proto_mail_mail_proto_goTypes = nil
	file_proto_mail_mail_proto_depIdxs = nil
}
