// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/mail/type/send_mail.proto

package mail

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Subject       string                 `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	DataMap       map[string]string      `protobuf:"bytes,4,rep,name=dataMap,proto3" json:"dataMap,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TemplateName  string                 `protobuf:"bytes,5,opt,name=templateName,proto3" json:"templateName,omitempty"`
	AckRequired   bool                   `protobuf:"varint,6,opt,name=ackRequired,proto3" json:"ackRequired,omitempty"`
	Priority      string                 `protobuf:"bytes,7,opt,name=priority,proto3" json:"priority,omitempty"`
	Domain        string                 `protobuf:"bytes,8,opt,name=domain,proto3" json:"domain,omitempty"`
	Cc            []string               `protobuf:"bytes,9,rep,name=cc,proto3" json:"cc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MailRequest) Reset() {
	*x = MailRequest{}
	mi := &file_proto_mail_type_send_mail_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailRequest) ProtoMessage() {}

func (x *MailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mail_type_send_mail_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailRequest.ProtoReflect.Descriptor instead.
func (*MailRequest) Descriptor() ([]byte, []int) {
	return file_proto_mail_type_send_mail_proto_rawDescGZIP(), []int{0}
}

func (x *MailRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *MailRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *MailRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *MailRequest) GetDataMap() map[string]string {
	if x != nil {
		return x.DataMap
	}
	return nil
}

func (x *MailRequest) GetTemplateName() string {
	if x != nil {
		return x.TemplateName
	}
	return ""
}

func (x *MailRequest) GetAckRequired() bool {
	if x != nil {
		return x.AckRequired
	}
	return false
}

func (x *MailRequest) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

func (x *MailRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *MailRequest) GetCc() []string {
	if x != nil {
		return x.Cc
	}
	return nil
}

type NewMailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Subject       string                 `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	DataMap       map[string]*anypb.Any  `protobuf:"bytes,4,rep,name=dataMap,proto3" json:"dataMap,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TemplateName  string                 `protobuf:"bytes,5,opt,name=templateName,proto3" json:"templateName,omitempty"`
	AckRequired   bool                   `protobuf:"varint,6,opt,name=ackRequired,proto3" json:"ackRequired,omitempty"`
	Priority      string                 `protobuf:"bytes,7,opt,name=priority,proto3" json:"priority,omitempty"`
	Domain        string                 `protobuf:"bytes,8,opt,name=domain,proto3" json:"domain,omitempty"`
	Cc            []string               `protobuf:"bytes,9,rep,name=cc,proto3" json:"cc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewMailRequest) Reset() {
	*x = NewMailRequest{}
	mi := &file_proto_mail_type_send_mail_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewMailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewMailRequest) ProtoMessage() {}

func (x *NewMailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mail_type_send_mail_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewMailRequest.ProtoReflect.Descriptor instead.
func (*NewMailRequest) Descriptor() ([]byte, []int) {
	return file_proto_mail_type_send_mail_proto_rawDescGZIP(), []int{1}
}

func (x *NewMailRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *NewMailRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *NewMailRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *NewMailRequest) GetDataMap() map[string]*anypb.Any {
	if x != nil {
		return x.DataMap
	}
	return nil
}

func (x *NewMailRequest) GetTemplateName() string {
	if x != nil {
		return x.TemplateName
	}
	return ""
}

func (x *NewMailRequest) GetAckRequired() bool {
	if x != nil {
		return x.AckRequired
	}
	return false
}

func (x *NewMailRequest) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

func (x *NewMailRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *NewMailRequest) GetCc() []string {
	if x != nil {
		return x.Cc
	}
	return nil
}

type MailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	CorrelationId string                 `protobuf:"bytes,3,opt,name=correlationId,proto3" json:"correlationId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MailResponse) Reset() {
	*x = MailResponse{}
	mi := &file_proto_mail_type_send_mail_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailResponse) ProtoMessage() {}

func (x *MailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mail_type_send_mail_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailResponse.ProtoReflect.Descriptor instead.
func (*MailResponse) Descriptor() ([]byte, []int) {
	return file_proto_mail_type_send_mail_proto_rawDescGZIP(), []int{2}
}

func (x *MailResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *MailResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *MailResponse) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

var File_proto_mail_type_send_mail_proto protoreflect.FileDescriptor

const file_proto_mail_type_send_mail_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/mail/type/send_mail.proto\x12\x04mail\x1a\x19google/protobuf/any.proto\"\xcb\x02\n" +
	"\vMailRequest\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\x12\x18\n" +
	"\asubject\x18\x03 \x01(\tR\asubject\x128\n" +
	"\adataMap\x18\x04 \x03(\v2\x1e.mail.MailRequest.DataMapEntryR\adataMap\x12\"\n" +
	"\ftemplateName\x18\x05 \x01(\tR\ftemplateName\x12 \n" +
	"\vackRequired\x18\x06 \x01(\bR\vackRequired\x12\x1a\n" +
	"\bpriority\x18\a \x01(\tR\bpriority\x12\x16\n" +
	"\x06domain\x18\b \x01(\tR\x06domain\x12\x0e\n" +
	"\x02cc\x18\t \x03(\tR\x02cc\x1a:\n" +
	"\fDataMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe7\x02\n" +
	"\x0eNewMailRequest\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\x12\x18\n" +
	"\asubject\x18\x03 \x01(\tR\asubject\x12;\n" +
	"\adataMap\x18\x04 \x03(\v2!.mail.NewMailRequest.DataMapEntryR\adataMap\x12\"\n" +
	"\ftemplateName\x18\x05 \x01(\tR\ftemplateName\x12 \n" +
	"\vackRequired\x18\x06 \x01(\bR\vackRequired\x12\x1a\n" +
	"\bpriority\x18\a \x01(\tR\bpriority\x12\x16\n" +
	"\x06domain\x18\b \x01(\tR\x06domain\x12\x0e\n" +
	"\x02cc\x18\t \x03(\tR\x02cc\x1aP\n" +
	"\fDataMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\x05value:\x028\x01\"f\n" +
	"\fMailResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12$\n" +
	"\rcorrelationId\x18\x03 \x01(\tR\rcorrelationIdB\x0fZ\rgenproto/mailb\x06proto3"

var (
	file_proto_mail_type_send_mail_proto_rawDescOnce sync.Once
	file_proto_mail_type_send_mail_proto_rawDescData []byte
)

func file_proto_mail_type_send_mail_proto_rawDescGZIP() []byte {
	file_proto_mail_type_send_mail_proto_rawDescOnce.Do(func() {
		file_proto_mail_type_send_mail_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_mail_type_send_mail_proto_rawDesc), len(file_proto_mail_type_send_mail_proto_rawDesc)))
	})
	return file_proto_mail_type_send_mail_proto_rawDescData
}

var file_proto_mail_type_send_mail_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_mail_type_send_mail_proto_goTypes = []any{
	(*MailRequest)(nil),    // 0: mail.MailRequest
	(*NewMailRequest)(nil), // 1: mail.NewMailRequest
	(*MailResponse)(nil),   // 2: mail.MailResponse
	nil,                    // 3: mail.MailRequest.DataMapEntry
	nil,                    // 4: mail.NewMailRequest.DataMapEntry
	(*anypb.Any)(nil),      // 5: google.protobuf.Any
}
var file_proto_mail_type_send_mail_proto_depIdxs = []int32{
	3, // 0: mail.MailRequest.dataMap:type_name -> mail.MailRequest.DataMapEntry
	4, // 1: mail.NewMailRequest.dataMap:type_name -> mail.NewMailRequest.DataMapEntry
	5, // 2: mail.NewMailRequest.DataMapEntry.value:type_name -> google.protobuf.Any
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_mail_type_send_mail_proto_init() }
func file_proto_mail_type_send_mail_proto_init() {
	if File_proto_mail_type_send_mail_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_mail_type_send_mail_proto_rawDesc), len(file_proto_mail_type_send_mail_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_mail_type_send_mail_proto_goTypes,
		DependencyIndexes: file_proto_mail_type_send_mail_proto_depIdxs,
		MessageInfos:      file_proto_mail_type_send_mail_proto_msgTypes,
	}.Build()
	File_proto_mail_type_send_mail_proto = out.File
	file_proto_mail_type_send_mail_proto_goTypes = nil
	file_proto_mail_type_send_mail_proto_depIdxs = nil
}
